# Generated by Django 2.2.15 on 2020-09-05 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='approved_todo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todolist.Post'),
        ),
    ]
