# Generated by Django 2.2.15 on 2020-09-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='approved_todo',
            field=models.BooleanField(default=False),
        ),
    ]
